### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by umanking** [kosslab-kr/gitCodeShare.com#222]
- [ ] Other SNS plugin 

- [ ] Editor Capture over 1 page

- [ ] Contributor Profile (GitHub API Cache) 

- [ ] Puppeteer capture GET -> POST
